[package]
name = "neat"
version = "0.1.0"
edition = "2021"

[dependencies.hashbrown]
version = "0.15.0"
features = ["default-hasher"]
default-features = false

[dependencies.rand]
version = "0.8.5"
# default-features = false

# - consider using derivative crate, code would be cleaner and less cluttered
# - need to create custom error types, will prob use thiserror
# - need to figure out how to implement serialize and deserialize for types
