[package]
name = "neat"
version = "0.1.0"
edition = "2021"

[dependencies.hashbrown]
version = "0.15.1"
features = ["default-hasher"]
default-features = false

[dependencies.rand]
version = "0.8.5"
features = ["small_rng"]
default-features = false
