[package]
name = "neat"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = { version = "0.8.5", default-features = false }
rand_distr = { version = "0.4.3", default-features = false }
rayon = { version = "1.10.0", optional = true }

[dev-dependencies]
# rand = "0.8.5"
# itertools = "0.13.0"
# pretty_assertions = "1.4.0"

[features]
default = []
rayon = ["dep:rayon"]

